<?php
/**
 * @SWG\Swagger(
 *      basePath="/[service_alias]/anc",
 *     	host="[server]",
 *    	schemes={"[protocol]"},
 *     	produces={  
 *          "application/json",
            "application/xml",
            "text/html"
 * 		},
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Anc Test Rest",
 *         description="All fetaures to access server operation for anc",
 *     )
 * )
 */
?>

<h1 class="titleOverview">Service Anc</h1>
<p>
	<a class="linkOverview" href="javascript:sService='anc';LoadApi()">Anc</a>: this is the most comprehensive service which should be used as a preference when developing applications communicating with Anc. Those services allow you to administrate Anc applications.
</p>