<?php
/**
 * @SWG\Swagger(
 *      basePath="/[service_alias]/vitis",
 *     	host="[server]",
 *    	schemes={"[protocol]"},
 *   produces={ 
 *          "application/json",
            "application/xml",
            "text/html"
 * 		},
 * consumes={"application/json"}, 
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Vitis Test Rest",
 *         description="All fetaures to access server operation for vitis",
 *     )
 * 
 * )
 */
?>

<h1 class="titleOverview">Service Vitis</h1>
<p>
	<a class="linkOverview" href="javascript:sService='vitis';LoadApi()">Vitis :</a> this is the most comprehensive service which should be used as a preference when developing applications communicating with Vitis. Those services allow you to administrate vitis applications.
</p>