<?php
$properties['schema_vmap'] = 's_vmap';
$properties['use_proxy_for_tiles'] = false;
$properties['websocket_server'] = '127.0.0.1';
$properties['websocket_port'] = 8000;
$properties["cadastre"]["api"] = "cadastreV2";
$properties['print']['equality_timeout'] = 3000;
$properties['print']['tile_size'] = 1024;
$properties['print']['features_zoom'] = 100;
$properties['print']['quality'] = 100;
?>