<?php
$properties['schema_vmap'] = 's_vmap';
$properties['use_proxy_for_tiles'] = false;
$properties["cadastre"]["api"] = "cadastreV2";
$properties['print']['equality_timeout'] = 3000;
$properties['print']['tile_size'] = 1024;
$properties['print']['features_zoom'] = 100;
$properties['print']['quality'] = 100;
$properties["use_veremap_api"] = false;
$properties["use_vm4ms_api"] = true;
$properties["owner_login"] = 'u_vitis';
$properties["owner_pass"] = '';
?>
