<?php
/**
 * @SWG\Swagger(
 *      basePath="/[service_alias]/vm4ms",
 *     	host="[server]",
 *    	schemes={"[protocol]"},
 *     	produces={  
 *          "application/json",
            "application/xml",
            "text/html"
 * 		},
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="vMap4MapServer Test Rest",
 *         description="All features to access server operation for vMap4MapServer",
 *     )
 * )
 */
?>

<h1 class="titleOverview">Service vMap4MapServer</h1>
<p>
	<a class="linkOverview" href="javascript:sService='vm4ms';LoadApi()">vMap4MapServer :</a> this is the most comprehensive service which should be used as a preference when developing applications communicating with vMap4MapServer. Those services allow you to administrate vMap4MapServer applications.
</p>