<?php
    $properties["schema_anc"] = 's_anc';
    $properties["anc"]["cont_zone_urba"]["intersect"]["schema"] = '';
    $properties["anc"]["cont_zone_urba"]["intersect"]["table"] = '';
    $properties["anc"]["cont_zone_urba"]["intersect"]["column"] = '';
    $properties["anc"]["cont_zone_urba"]["intersect"]["column_geom"] = '';
    $properties["anc"]["code_postal"]["schema"] = '';
    $properties["anc"]["code_postal"]["table"] = '';
    $properties["anc"]["code_postal"]["column"] = '';
?>