<?php
/**
 * @SWG\Swagger(
 *      basePath="/[service_alias]/cadastreV2",
 *     	host="[server]",
 *    	schemes={"[protocol]"},
 *     	produces={  
 *          "application/json",
  "application/xml",
  "text/html"
 * 		},
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Cadastre Test Rest",
 *         description="All features to access server operation for cadastre",
 *     )
 * )
 */
?>

<h1 class="titleOverview">Service Cadastre Version 2 </h1>
<p>
    <a class="linkOverview" href="javascript:sService='cadastreV2';LoadApi()">CadastreV2</a>: this is the most comprehensive service which should be used as a preference when developing applications communicating with Cadastre. Those services allow you to administrate Cadastre applications.
</p>