<?php
/**
 * @SWG\Swagger(
 *      basePath="/[service_alias]/vmap",
 *     	host="[server]",
 *    	schemes={"[protocol]"},
 *     	produces={  
 *          "application/json",
  "application/xml",
  "text/html"
 * 		},
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Vmap Test Rest",
 *         description="All features to access server operation for vmap",
 *     )
 * )
 */
?>

<h1 class="titleOverview">Service Vmap</h1>
<p>
    <a class="linkOverview" href="javascript:sService='vmap';LoadApi()">Vmap</a>: service which should be used when developing applications communicating with Vmap. This service allows you to administrate Vmap application.
</p>