<?php
/**
 * @SWG\Swagger(
 *      basePath="/[service_alias]/vmap",
 *     	host="[server]",
 *    	schemes={"[protocol]"},
 *     	produces={  
 *          "application/json",
            "application/xml",
            "text/html"
 * 		},
 *     @SWG\Info(
 *         version="1.0.0",
 *         title="Vmap Test Rest",
 *         description="All fetaures to access server operation for vmap",
 *     )
 * )
 */
?>

<h1 class="titleOverview">Service Vmap</h1>
<p>
	<a class="linkOverview" href="javascript:sService='vmap';LoadApi()">Vmap</a>: this is the most comprehensive service which should be used as a preference when developing applications communicating with Vmap. Those services allow you to administrate Vmap applications.
</p>