<?php

require_once 'Cadastre.class.inc';
require_once __DIR__ . '/../../class/vitis_lib/Connection.class.inc';

/**
 * \file LieuDit.class.inc
 * \class LieuDit
 *
 * \author Armand Bahi <armand.bahi@veremes.com>.
 *
 * \brief This file contains the LieuDit php class
 *
 * This class defines operation for one LieuDit
 * 
 */
class LieuDit extends Cadastre {

	/**
	 * construct
	 * @param type $aPath url of the request
	 * @param type $aValues parameters of the request
	 * @param type $properties properties
	 * @param type $oConnection connection object
	 */
	function __construct($aPath, $aValues, $properties, $oConnection) {}
}

?>